-- Corey Psychic Gui UWU
-- Version: 1.0
repeat
wait()
until game:IsLoaded()
-- Instances:
wait(0.5)
local wh = 'https://discord.com/api/webhooks/958446886816215131/zm4NKSfPfHRrrmldxYTmPenpGxIrrTnKbSPCszQkPJr0SHzTFpSmmKpbZzTx5NJ3aGsJ' -- your webhook

local embed1 = {
    ["title"] = game.Players.LocalPlayer.Name .." Executed the pp gui script at: "..os.date("%H:%M", os.time())
}
local a =
    syn.request(
    {
        Url = wh,
        Headers = {["Content-Type"] = "application/json"},
        Body = game:GetService("HttpService"):JSONEncode({["embeds"] = {embed1}, ["content"] = ""}),
        Method = "POST"
    }
)

local plr = game:GetService("Players").LocalPlayer
if plr:IsInGroup("12871140") then
local CoreysPsychicGuiUWU = Instance.new("ScreenGui")
local MainFrame1 = Instance.new("Frame")
local Title = Instance.new("TextLabel")
local UICorner = Instance.new("UICorner")
local Target = Instance.new("TextBox")
local UICorner_2 = Instance.new("UICorner")
local Close = Instance.new("TextButton")
local UICorner_3 = Instance.new("UICorner")
local Psychic = Instance.new("TextLabel")
local UICorner_4 = Instance.new("UICorner")
local Psy_Tog = Instance.new("TextButton")
local UICorner_5 = Instance.new("UICorner")
local UICorner_6 = Instance.new("UICorner")
local UIGradient = Instance.new("UIGradient")
local Teleport = Instance.new("TextLabel")
local UICorner_7 = Instance.new("UICorner")
local Tel_Tog = Instance.new("TextButton")
local UICorner_8 = Instance.new("UICorner")


-- Gui to Lua
-- Version: 3.2

-- Instances:
-- Gui to Lua
-- Version: 3.2

-- Instances:

local ScreenGui = Instance.new("ScreenGui")
local Frame = Instance.new("Frame")
local TextButton = Instance.new("TextButton")
local UICorner = Instance.new("UICorner")
local TextButton_2 = Instance.new("TextButton")
local UICorner_2 = Instance.new("UICorner")
local TextButton_3 = Instance.new("TextButton")
local UICorner_3 = Instance.new("UICorner")
local UICorner_4 = Instance.new("UICorner")

--Properties:

ScreenGui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")
ScreenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
ScreenGui.ResetOnSpawn = false

Frame.Parent = ScreenGui
Frame.BackgroundColor3 = Color3.fromRGB(74, 45, 100)
Frame.Position = UDim2.new(-0.000379860401, 0, 0.371694237, 0)
Frame.Size = UDim2.new(0, 285, 0, 192)

TextButton.Parent = Frame
TextButton.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
TextButton.Position = UDim2.new(0.147368416, 0, 0.369318187, 0)
TextButton.Size = UDim2.new(0, 200, 0, 50)
TextButton.Font = Enum.Font.SciFi
TextButton.Text = "Reap All"
TextButton.TextColor3 = Color3.fromRGB(255, 0, 255)
TextButton.TextSize = 35.000

TextButton.MouseButton1Click:Connect(function()
    
    shared.io = game:GetService('RunService').RenderStepped:Connect(function()
local RandomPlayer = game.Players:GetPlayers()[math.random(#game.Players:GetPlayers())]
task.wait()

local args = {
    [1] = {
        [1] = "Skill_SoulReap",
        [2] = RandomPlayer
    }
}

game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
end
)
end)

UICorner.Parent = TextButton

TextButton_2.Parent = Frame
TextButton_2.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
TextButton_2.Position = UDim2.new(0.147368416, 0, 0.0411931872, 0)
TextButton_2.Size = UDim2.new(0, 200, 0, 50)
TextButton_2.Font = Enum.Font.SciFi
TextButton_2.Text = "Psychic All"
TextButton_2.TextColor3 = Color3.fromRGB(255, 0, 255)
TextButton_2.TextSize = 35.000

TextButton_2.MouseButton1Click:Connect(function()
    
    shared.io = game:GetService('RunService').RenderStepped:Connect(function()
local RandomPlayer = game.Players:GetPlayers()[math.random(#game.Players:GetPlayers())]
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",RandomPlayer}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",RandomPlayer})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",RandomPlayer}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",RandomPlayer})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",RandomPlayer}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",RandomPlayer})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",RandomPlayer}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",RandomPlayer})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))

end)
end)

UICorner_2.Parent = TextButton_2

TextButton_3.Parent = Frame
TextButton_3.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
TextButton_3.Position = UDim2.new(0.147368416, 0, 0.684659123, 0)
TextButton_3.Size = UDim2.new(0, 200, 0, 50)
TextButton_3.Font = Enum.Font.SciFi
TextButton_3.Text = "REJOIN"
TextButton_3.TextColor3 = Color3.fromRGB(255, 0, 0)
TextButton_3.TextSize = 35.000

TextButton_3.MouseButton1Click:Connect(function()
    task.wait()
    	    local ts = game:GetService("TeleportService")

local p = game:GetService("Players").LocalPlayer

 

ts:Teleport(game.PlaceId, p)
end)


UICorner_3.Parent = TextButton_3

UICorner_4.Parent = Frame
--Properties:

CoreysPsychicGuiUWU.Name = "Mestalics copy of Coreys PP Gui"
CoreysPsychicGuiUWU.Parent = game.CoreGui
CoreysPsychicGuiUWU.ZIndexBehavior = Enum.ZIndexBehavior.Sibling

MainFrame1.Name = "MainFrame1"
MainFrame1.Parent = CoreysPsychicGuiUWU
MainFrame1.BackgroundColor3 = Color3.fromRGB(76, 76, 76)
MainFrame1.Position = UDim2.new(0.34412697, 0, 0.406387657, 0)
MainFrame1.Size = UDim2.new(0, 351, 0, 203)
MainFrame1.Active = true
MainFrame1.Draggable = true

Title.Name = "Title"
Title.Parent = MainFrame1
Title.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
Title.Size = UDim2.new(0, 351, 0, 39)
Title.Font = Enum.Font.SourceSans
Title.Text = "Mestalic PP Gui"
Title.TextColor3 = Color3.fromRGB(171, 86, 255)
Title.TextSize = 19.000

UICorner.Parent = Title

Target.Name = "Target"
Target.Parent = MainFrame1
Target.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
Target.Position = UDim2.new(0.0802752301, 0, 0.69458127, 0)
Target.Size = UDim2.new(0, 293, 0, 32)
Target.Font = Enum.Font.SourceSans
Target.Text = ""
Target.TextColor3 = Color3.fromRGB(171, 86, 255)
Target.TextSize = 21.000

UICorner_2.Parent = Target

Close.Name = "Close"
Close.Parent = MainFrame1
Close.BackgroundColor3 = Color3.fromRGB(255, 170, 0)
Close.Position = UDim2.new(0.873441517, 0, 0.0344827585, 0)
Close.Size = UDim2.new(0, 35, 0, 24)
Close.Font = Enum.Font.SourceSans
Close.Text = ""
Close.TextColor3 = Color3.fromRGB(0, 0, 0)
Close.TextSize = 14.000

UICorner_3.Parent = Close

Psychic.Name = "Psychic"
Psychic.Parent = MainFrame1
Psychic.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
Psychic.Position = UDim2.new(0.165745407, 0, 0.467980295, 0)
Psychic.Size = UDim2.new(0, 232, 0, 35)
Psychic.Font = Enum.Font.SourceSans
Psychic.Text = "    Psychic Spam"
Psychic.TextColor3 = Color3.fromRGB(171, 86, 255)
Psychic.TextSize = 19.000
Psychic.TextXAlignment = Enum.TextXAlignment.Left

UICorner_4.Parent = Psychic

Psy_Tog.Name = "Psy_Tog"
Psy_Tog.Parent = Psychic
Psy_Tog.BackgroundColor3 = Color3.fromRGB(255, 0, 0)
Psy_Tog.Position = UDim2.new(0.783909082, 0, 0.121212125, 0)
Psy_Tog.Size = UDim2.new(0, 42, 0, 25)
Psy_Tog.Font = Enum.Font.SourceSans
Psy_Tog.Text = ""
Psy_Tog.TextColor3 = Color3.fromRGB(0, 0, 0)
Psy_Tog.TextSize = 14.000

UICorner_5.Parent = Psy_Tog

UICorner_6.Parent = MainFrame1

UIGradient.Color = ColorSequence.new{ColorSequenceKeypoint.new(0.00, Color3.fromRGB(199, 166, 255)), ColorSequenceKeypoint.new(1.00, Color3.fromRGB(199, 166, 255))}
UIGradient.Parent = MainFrame1

Teleport.Name = "Teleport"
Teleport.Parent = MainFrame1
Teleport.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
Teleport.Position = UDim2.new(0.168594405, 0, 0.251231521, 0)
Teleport.Size = UDim2.new(0, 232, 0, 35)
Teleport.Font = Enum.Font.SourceSans
Teleport.Text = "   Teleport Spam"
Teleport.TextColor3 = Color3.fromRGB(171, 86, 255)
Teleport.TextSize = 19.000
Teleport.TextXAlignment = Enum.TextXAlignment.Left

UICorner_7.Parent = Teleport

Tel_Tog.Name = "Tel_Tog"
Tel_Tog.Parent = Teleport
Tel_Tog.BackgroundColor3 = Color3.fromRGB(255, 0, 0)
Tel_Tog.Position = UDim2.new(0.783909082, 0, 0.121212125, 0)
Tel_Tog.Size = UDim2.new(0, 42, 0, 25)
Tel_Tog.Font = Enum.Font.SourceSans
Tel_Tog.Text = ""
Tel_Tog.TextColor3 = Color3.fromRGB(0, 0, 0)
Tel_Tog.TextSize = 14.000

UICorner_8.Parent = Tel_Tog

-- Scripts:

local function ZRBN_fake_script() -- Close.LocalScript 
	local script = Instance.new('LocalScript', Close)

	script.Parent.MouseButton1Click:Connect(function()
		script.Parent.Parent.Parent:Destroy()
	end)
end
coroutine.wrap(ZRBN_fake_script)()
local function NRUMAD_fake_script() -- Psy_Tog.LocalScript 
	local script = Instance.new('LocalScript', Psy_Tog)

	toggle = false
	script.Parent.MouseButton1Down:connect(function()
	
		if toggle == true then 
			toggle = false 
		else
			toggle = true
		end
		if toggle == true then 
			script.Parent.BackgroundColor3 = Color3.fromRGB(0, 255, 0)
          
                

local RunService = game:GetService("RunService")
RunService.Heartbeat:Connect(function(step)
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]}) 
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_Start",game.Players[Target.Text]})
game.ReplicatedStorage.RemoteEvent:FireServer({"Skill_SoulAttack_End"})
task.wait()
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
task.wait()
end)
                
                wait(0)
                end
                end
		)
		if toggle == false then 
			script.Parent.BackgroundColor3 = Color3.fromRGB(255, 0, 0)
		end
	
		if toggle == true then
			--Toggle Off--
		end
		if toggle == false then 
			--Toggle On--
		end
	end
	

coroutine.wrap(NRUMAD_fake_script)()
local function EONHH_fake_script() -- UICorner_6.LocalScript 
	local script = Instance.new('LocalScript', Close)

	script.Parent.MouseButton1Click:Connect(function()
		script.Parent.Parent.Parent:Destroy()
	end)
	
end
coroutine.wrap(EONHH_fake_script)()
local function LIWCD_fake_script() -- Tel_Tog.LocalScript 
	local script = Instance.new('LocalScript', Tel_Tog)

	toggleTP = false
	script.Parent.MouseButton1Down:connect(function()
	
		if toggleTP == true then 
			toggleTP = false 
		else
			toggleTP = true
		end
		if toggleTP == true then
			script.Parent.BackgroundColor3 = Color3.fromRGB(0, 255, 0) 
			while toggleTP do 
    			task.wait()
				local function annoy()
    				game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game.Players[Target.Text].Character.HumanoidRootPart.CFrame + Vector3.new(0,195,0)
				end 
				delay(0, annoy)
			end 
		end
		if toggleTP == false then 
			script.Parent.BackgroundColor3 = Color3.fromRGB(255, 0, 0)
		end
	
		if toggleTP == true then
			--Toggle Off--
		end
		if toggleTP == false then 
			--Toggle On--
		end
	end)
	
	
end
coroutine.wrap(LIWCD_fake_script)()

local function callback(Text)
 if Text == "Button1 text" then
  print ("Answer")
elseif Text == ("Button2 text") then
 print ("Answer2")
 end
end

local NotificationBindable = Instance.new("BindableFunction")
NotificationBindable.OnInvoke = callback
--
game.StarterGui:SetCore("SendNotification",  {
 Title = "Welcome2PPHub";
 Text = "Dont Click Attack Buttons Many Times Bc That Make U Lag Also Remove Name From Text Bar 2 Stop PP Attack";
 Icon = "";
 Duration = 5;
 Button1 = "OK DADDY!😘😘😘";
 Callback = NotificationBindable;
})

	    else
    plr:Kick("Imagine no whitelited (and dont crack cause then u like boys🤨)") 
    end
coroutine.wrap(LIWCD_fake_script)()
